### ISSUE TITLE
error in neural-collision-model

### ISSUE THREAD

**Issue by SamiraMalek** [lettucecfd/lettuce-paper#5]
Hi,
I have installed lettuce. But when I run script.py from neural-collision-model folder I receive the following error:
Traceback (most recent call last):
  File "script.py", line 358, in <module>
    simulation_p = Simulation(flow=flow_coarse, lattice=lattice, collision=collision_coarse, streaming=streaming)
  File "/scratch/sxm6547/lettuce/lettuce/simulation.py", line 85, in __init__
    if not self.collision.native_available():
  File "/scratch/sxm6547/anaconda3/envs/Samira/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LearnedMRT' object has no attribute 'native_available'

**Comment by Olllom** [comment]
Hi, thanks for letting us know about this error. The problem here is a recent error in the lettuce API. Try with lettuce 0.2.3 (git checkout 0.2.3)

**Comment by SamiraMalek** [comment]
Hi,
I have executed the code for the neural-collision-model, and the output displayed for the section titled **"Comparison with other collision models"** (located between lines 330 and 392) appears as follows:
```
                                      Velocity            Density           Energy            Enstrophy
Learned collision       3.2722e-03     3.3333e-05    4.1643e-06     3.9876e+00
BGKCollision              2.9373e-02     5.4276e-05    2.8729e-06     1.1155e+00
```
I've observed that the Mean Squared Error (MSE) for the BGKCollision with a grid size of 64x64 is lower compared to that of the Learned collision. However, what's interesting is that the outputs of the Neural LBM (which, to my understanding, is equivalent to the Learned collision), it is more closely aligned with the output of BGKCollision using a grid size of 128x128, rather than the output from BGKCollision with a grid size of 64x64 at Figure 4 in the paper.

I'm intrigued by the higher MSE values for Velocity, Energy, and Enstrophy in the Learned collision model, particularly when compared to the BGKCollision model with a grid size of 64x64. Could you please shed some light on the reasons behind this discrepancy?
